### ISSUE TITLE
Teilnehmerliste - neuer Skatabend

### ISSUE THREAD

**Issue by thbemme** [christian-wtd/skatit#18]
Da ja bei einem Skatabend immer mindestens drei Spieler dabei sind, könnte man die Teilnehmerliste auch über Pulldown Schaltflächen eingeben, also vorgegeben:

![image](https://user-images.githubusercontent.com/14074615/35450653-efe116c0-02c0-11e8-9110-1b2620ca11b2.png)
Im gelben Bereich sind dann die pull down Menüs mit allen eingetragenen Spielern und am Ende "neu" für einen neuen Spieler.

Sind alle Spieler eingetragen, wird automatisch eine neue Zeile abgehangen, um weitere Spieler aufnehmen zu können.

Das erspart nerviges Klicken.

**Comment by christian-wtd** [comment]
Klingt ganz gut, ich schaue mal, was sich machen lässt.

**Comment by christian-wtd** [comment]
Implementation done:
- Teilnehmer direkt am Skatevent, nicht mehr als separate Seite.
- Teilnehmer nicht lösch/editierbar, falls schon ein Spiel vorhanden
- Zeilen nur einzeln hinzufügbar/editierbar, da sonst das Form extrem kompliziert wird :-P
- deshalb auch keine 3 bereits existierenden Zeilen

bitte mal anschauen und kommentieren, (ist im Heroku schon Live)
