### ISSUE TITLE
Buben im Spiel

### ISSUE THREAD

**Issue by thbemme** [christian-wtd/skatit#19]
Beim erstelle eines neuen Spiels sollte man einfach die gespielten Buben auswählen können - das erspart nerviges Klicken - der Rest muss dann natürlich vom Programm berechnet werden.

**Comment by christian-wtd** [comment]
Bitte Idee als Mockup bauen.
Erfahrung: Meist ist es schon schwer für die Spieler sich zu erinnern, welche Anzahl Buben sie hatten geschweige denn, welche.

**Comment by christian-wtd** [comment]
Habe mal ein paar Ideen ausprobiert, Ergebnis:
Abgelehnt, da nicht nur Buben Trumpf sein können und das dann unübersichtlich wird
außerdem wäre das eklig zu implementieren.
